# 데이터 로딩

In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets

mnist = datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


# 필요한 레이어들 불러오기
* `Flatten`
* `Dense`
* 레이어들을 순서대로 엮어줄 `Sequential` 모델 가져오기
  * `OrderedDict`의 역할
  * `tensorflow.keras.models`에 `Sequential`클래스가 있음

* Input 레이어가 굳이 없어도 된다. 단 첫 번째 레이어에 입력 데이터의 형상을 지정(`input_shape`)

In [ ]:
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential

`Sequential`모델링은 단순하게 파이썬의 리스트에 레이어를 추가시키는 개념

In [ ]:
model = Sequential([.
  Flatten(input_shape=(28, 28)),
  Dense(512, activation='relu'),
  Dense(256, activation='relu'),
  Dense(128, activation='relu'),
  Dense(64, activation='relu'),
  Dense(32, activation='relu'),
  Dense(10, activation='softmax'),
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_7 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_8 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_9 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_10 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_11 (Dense)             (None, 10)               

모델 컴파일

In [ ]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['acc']
)

훈련

In [ ]:
X_train = X_train / 255.
X_test  = X_test / 255.

model.fit(X_train,
          y_train,
          validation_data=(X_test, y_test),
          epochs=15,
          batch_size=32)

Epoch 1/15
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2240 - acc: 0.9334 - val_loss: 0.1310 - val_acc: 0.9589
Epoch 2/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1010 - acc: 0.9706 - val_loss: 0.0905 - val_acc: 0.9755
Epoch 3/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0708 - acc: 0.9792 - val_loss: 0.1056 - val_acc: 0.9705
Epoch 4/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0573 - acc: 0.9837 - val_loss: 0.0918 - val_acc: 0.9734
Epoch 5/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0478 - acc: 0.9858 - val_loss: 0.0845 - val_acc: 0.9793
Epoch 6/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0384 - acc: 0.9888 - val_loss: 0.0799 - val_acc: 0.9807
Epoch 7/15
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0327 - acc: 0.9905 - val_loss: 0.0730 - val_acc: 0.9814
Epoch 8/15
1875/1875 [==============================] - 4s 2ms

In [ ]:
model = Sequential()

model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(256, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_12 (Dense)             (None, 256)               200960    
_________________________________________________________________
dense_13 (Dense)             (None, 64)                16448     
_________________________________________________________________
dense_14 (Dense)             (None, 10)                650       
Total params: 218,058
Trainable params: 218,058
Non-trainable params: 0
_________________________________________________________________


# 실습
* 1층 : `Flatten`
* Dense(512, relu) - Dense(256-relu) - Dense(10 - softmax)
* y_train One Hot Encoding
* y_test도 One Hot Encoding
* optimizer - adam
* metrics - acc
* loss - ???

In [ ]:
y_train_one_hot = tf.one_hot(y_train, 10)
y_test_one_hot  = tf.one_hot(y_test, 10)

y_train_one_hot.shape, y_test_one_hot.shape

(TensorShape([60000, 10]), TensorShape([10000, 10]))

In [ ]:
y_train_one_hot[:3]

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
model = Sequential([
  Flatten(input_shape=(28, 28)),
  Dense(512, activation="relu"),
  Dense(256, activation="relu"),
  Dense(10, activation="softmax")
])

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_15 (Dense)             (None, 512)               401920    
_________________________________________________________________
dense_16 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_17 (Dense)             (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['acc']
)

In [ ]:
model.fit(
    X_train,
    y_train_one_hot,
    validation_split=0.2,
    epochs=10,
    batch_size=32
)

Epoch 1/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.2047 - acc: 0.9379 - val_loss: 0.1196 - val_acc: 0.9625
Epoch 2/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0842 - acc: 0.9735 - val_loss: 0.1049 - val_acc: 0.9672
Epoch 3/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0559 - acc: 0.9817 - val_loss: 0.1111 - val_acc: 0.9688
Epoch 4/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0437 - acc: 0.9855 - val_loss: 0.1110 - val_acc: 0.9714
Epoch 5/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0330 - acc: 0.9893 - val_loss: 0.1183 - val_acc: 0.9697
Epoch 6/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0286 - acc: 0.9899 - val_loss: 0.1039 - val_acc: 0.9749
Epoch 7/10
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0239 - acc: 0.9918 - val_loss: 0.0948 - val_acc: 0.9795
Epoch 8/10
1500/1500 [==============================] - 3s 2ms